#!/bin/bash

echo Running on host `hostname`
echo
echo Initial Time is `date`
echo
echo Directory is `pwd`
echo
echo ################

############# If running a sequential or openMP program

:> saida-bf.txt ; :> tempos-bf.txt

################ Sequencial
echo --- Sequencial ---
echo --- Sequencial --- >> saida-bf.txt
echo --- Sequencial --- >> tempos-bf.txt
./min-dist-bf-sequencial >> saida-bf.txt 2>> tempos-bf.txt

################ 2 Threads
export OMP_NUM_THREADS=2
echo --- 2 Threads ---
echo --- 2 Threads --- >> saida-bf.txt
echo --- 2 Threads --- >> tempos-bf.txt
./min-dist-bf >> saida-bf.txt 2>> tempos-bf.txt

################ 4 Threads
export OMP_NUM_THREADS=4
echo --- 4 Threads ---
echo --- 4 Threads --- >> saida-bf.txt
echo --- 4 Threads --- >> tempos-bf.txt
./min-dist-bf >> saida-bf.txt 2>> tempos-bf.txt

################ 8 Threads
export OMP_NUM_THREADS=8
echo --- 8 Threads ---
echo --- 8 Threads --- >> saida-bf.txt
echo --- 8 Threads --- >> tempos-bf.txt
./min-dist-bf >> saida-bf.txt 2>> tempos-bf.txt

################ 16 Threads
export OMP_NUM_THREADS=16
echo --- 16 Threads ---
echo --- 16 Threads --- >> saida-bf.txt
echo --- 16 Threads --- >> tempos-bf.txt
./min-dist-bf >> saida-bf.txt 2>> tempos-bf.txt


################

echo Final Time is `date`

