#!/bin/bash

echo Running on host `hostname`
echo
echo Initial Time is `date`
echo
echo Directory is `pwd`
echo
echo ################

############# If running a sequential or openMP program

:> saida-dc.txt ; :> tempos-dc.txt

################ Sequencial
echo --- Sequencial ---
echo --- Sequencial --- >> saida-dc.txt
echo --- Sequencial --- >> tempos-dc.txt
./min-dist-dc-sequencial >> saida-dc.txt 2>> tempos-dc.txt

################ 2 Nodos
export OMP_NUM_THREADS=2
echo --- 2 Nodos ---
echo --- 2 Nodos --- >> saida-dc.txt
echo --- 2 Nodos --- >> tempos-dc.txt
./min-dist-dc >> saida-dc.txt 2>> tempos-dc.txt

################ 4 Nodos
export OMP_NUM_THREADS=4
echo --- 4 Nodos ---
echo --- 4 Nodos --- >> saida-dc.txt
echo --- 4 Nodos --- >> tempos-dc.txt
./min-dist-dc >> saida-dc.txt 2>> tempos-dc.txt

################ 8 Nodos
export OMP_NUM_THREADS=8
echo --- 8 Nodos ---
echo --- 8 Nodos --- >> saida-dc.txt
echo --- 8 Nodos --- >> tempos-dc.txt
./min-dist-dc >> saida-dc.txt 2>> tempos-dc.txt

################ 16 Nodos
export OMP_NUM_THREADS=16
echo --- 16 Nodos ---
echo --- 16 Nodos --- >> saida-dc.txt
echo --- 16 Nodos --- >> tempos-dc.txt
./min-dist-dc >> saida-dc.txt 2>> tempos-dc.txt


################

echo Final Time is `date`

